language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

before_script:
  - mv src/utils/clientConfig.sample.js src/utils/clientConfig.js

script:
  - npm test

# safelist
branches:
  only:
  - develop