language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm test

before_script:
- mv /src/utils/clientConfig.sample.js /src/utils/clientConfig.js

# safelist
branches:
  only:
  - develop