// flow-typed signature: fd8c4331da8913cf44858df6e96643fc
// flow-typed version: <<STUB>>/dicty-components-redux_v2.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dicty-components-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dicty-components-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dicty-components-redux/lib/main' {
  declare module.exports: any;
}

declare module 'dicty-components-redux/lib/middleware/storage' {
  declare module.exports: any;
}

declare module 'dicty-components-redux/lib/utils/hydrateStore' {
  declare module.exports: any;
}

declare module 'dicty-components-redux/src/main' {
  declare module.exports: any;
}

declare module 'dicty-components-redux/src/middleware/storage' {
  declare module.exports: any;
}

declare module 'dicty-components-redux/src/utils/hydrateStore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dicty-components-redux/lib/main.js' {
  declare module.exports: $Exports<'dicty-components-redux/lib/main'>;
}
declare module 'dicty-components-redux/lib/middleware/storage.js' {
  declare module.exports: $Exports<'dicty-components-redux/lib/middleware/storage'>;
}
declare module 'dicty-components-redux/lib/utils/hydrateStore.js' {
  declare module.exports: $Exports<'dicty-components-redux/lib/utils/hydrateStore'>;
}
declare module 'dicty-components-redux/src/main.js' {
  declare module.exports: $Exports<'dicty-components-redux/src/main'>;
}
declare module 'dicty-components-redux/src/middleware/storage.js' {
  declare module.exports: $Exports<'dicty-components-redux/src/middleware/storage'>;
}
declare module 'dicty-components-redux/src/utils/hydrateStore.js' {
  declare module.exports: $Exports<'dicty-components-redux/src/utils/hydrateStore'>;
}
