// flow-typed signature: 9d5321a6a1ecb603324e58f85fa473c6
// flow-typed version: <<STUB>>/dicty-components-login_v1.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dicty-components-login'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dicty-components-login' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dicty-components-login/es/components/Login' {
  declare module.exports: any;
}

declare module 'dicty-components-login/es/index' {
  declare module.exports: any;
}

declare module 'dicty-components-login/es/styles/Buttons' {
  declare module.exports: any;
}

declare module 'dicty-components-login/es/styles/Container' {
  declare module.exports: any;
}

declare module 'dicty-components-login/lib/components/Login' {
  declare module.exports: any;
}

declare module 'dicty-components-login/lib/index' {
  declare module.exports: any;
}

declare module 'dicty-components-login/lib/styles/Buttons' {
  declare module.exports: any;
}

declare module 'dicty-components-login/lib/styles/Container' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dicty-components-login/es/components/Login.js' {
  declare module.exports: $Exports<'dicty-components-login/es/components/Login'>;
}
declare module 'dicty-components-login/es/index.js' {
  declare module.exports: $Exports<'dicty-components-login/es/index'>;
}
declare module 'dicty-components-login/es/styles/Buttons.js' {
  declare module.exports: $Exports<'dicty-components-login/es/styles/Buttons'>;
}
declare module 'dicty-components-login/es/styles/Container.js' {
  declare module.exports: $Exports<'dicty-components-login/es/styles/Container'>;
}
declare module 'dicty-components-login/lib/components/Login.js' {
  declare module.exports: $Exports<'dicty-components-login/lib/components/Login'>;
}
declare module 'dicty-components-login/lib/index.js' {
  declare module.exports: $Exports<'dicty-components-login/lib/index'>;
}
declare module 'dicty-components-login/lib/styles/Buttons.js' {
  declare module.exports: $Exports<'dicty-components-login/lib/styles/Buttons'>;
}
declare module 'dicty-components-login/lib/styles/Container.js' {
  declare module.exports: $Exports<'dicty-components-login/lib/styles/Container'>;
}
