// flow-typed signature: 34c85bf9483701061852096172e8ea6f
// flow-typed version: <<STUB>>/dicty-components-panel_v0.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dicty-components-panel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dicty-components-panel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dicty-components-panel/examples/App' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/examples/webpack.config' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/lib/Components/Panel' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/lib/Components/PanelBody' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/lib/Components/PanelGroup' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/lib/Components/PanelHeader' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/lib/Components/PanelTitle' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/lib/index' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/src/__tests__/Panel.spec' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/src/__tests__/PanelBody.spec' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/src/__tests__/PanelGroup.spec' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/src/__tests__/PanelHeader.spec' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/src/__tests__/PanelTitle.spec' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/src/Components/Panel' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/src/Components/PanelBody' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/src/Components/PanelGroup' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/src/Components/PanelHeader' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/src/Components/PanelTitle' {
  declare module.exports: any;
}

declare module 'dicty-components-panel/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dicty-components-panel/examples/App.js' {
  declare module.exports: $Exports<'dicty-components-panel/examples/App'>;
}
declare module 'dicty-components-panel/examples/webpack.config.js' {
  declare module.exports: $Exports<'dicty-components-panel/examples/webpack.config'>;
}
declare module 'dicty-components-panel/lib/Components/Panel.js' {
  declare module.exports: $Exports<'dicty-components-panel/lib/Components/Panel'>;
}
declare module 'dicty-components-panel/lib/Components/PanelBody.js' {
  declare module.exports: $Exports<'dicty-components-panel/lib/Components/PanelBody'>;
}
declare module 'dicty-components-panel/lib/Components/PanelGroup.js' {
  declare module.exports: $Exports<'dicty-components-panel/lib/Components/PanelGroup'>;
}
declare module 'dicty-components-panel/lib/Components/PanelHeader.js' {
  declare module.exports: $Exports<'dicty-components-panel/lib/Components/PanelHeader'>;
}
declare module 'dicty-components-panel/lib/Components/PanelTitle.js' {
  declare module.exports: $Exports<'dicty-components-panel/lib/Components/PanelTitle'>;
}
declare module 'dicty-components-panel/lib/index.js' {
  declare module.exports: $Exports<'dicty-components-panel/lib/index'>;
}
declare module 'dicty-components-panel/src/__tests__/Panel.spec.js' {
  declare module.exports: $Exports<'dicty-components-panel/src/__tests__/Panel.spec'>;
}
declare module 'dicty-components-panel/src/__tests__/PanelBody.spec.js' {
  declare module.exports: $Exports<'dicty-components-panel/src/__tests__/PanelBody.spec'>;
}
declare module 'dicty-components-panel/src/__tests__/PanelGroup.spec.js' {
  declare module.exports: $Exports<'dicty-components-panel/src/__tests__/PanelGroup.spec'>;
}
declare module 'dicty-components-panel/src/__tests__/PanelHeader.spec.js' {
  declare module.exports: $Exports<'dicty-components-panel/src/__tests__/PanelHeader.spec'>;
}
declare module 'dicty-components-panel/src/__tests__/PanelTitle.spec.js' {
  declare module.exports: $Exports<'dicty-components-panel/src/__tests__/PanelTitle.spec'>;
}
declare module 'dicty-components-panel/src/Components/Panel.js' {
  declare module.exports: $Exports<'dicty-components-panel/src/Components/Panel'>;
}
declare module 'dicty-components-panel/src/Components/PanelBody.js' {
  declare module.exports: $Exports<'dicty-components-panel/src/Components/PanelBody'>;
}
declare module 'dicty-components-panel/src/Components/PanelGroup.js' {
  declare module.exports: $Exports<'dicty-components-panel/src/Components/PanelGroup'>;
}
declare module 'dicty-components-panel/src/Components/PanelHeader.js' {
  declare module.exports: $Exports<'dicty-components-panel/src/Components/PanelHeader'>;
}
declare module 'dicty-components-panel/src/Components/PanelTitle.js' {
  declare module.exports: $Exports<'dicty-components-panel/src/Components/PanelTitle'>;
}
declare module 'dicty-components-panel/src/index.js' {
  declare module.exports: $Exports<'dicty-components-panel/src/index'>;
}
