// flow-typed signature: 6d270223d10ffe83d73b8731827e48ad
// flow-typed version: <<STUB>>/draft-js-buttons_v2.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-buttons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-buttons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-buttons/lib/components/AlignBlockCenterButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/AlignBlockDefaultButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/AlignBlockLeftButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/AlignBlockRightButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/BlockquoteButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/BoldButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/CodeBlockButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/CodeButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/HeadlineOneButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/HeadlineThreeButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/HeadlineTwoButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/ItalicButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/OrderedListButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/SubButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/SupButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/UnderlineButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/components/UnorderedListButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/utils/createBlockAlignmentButton' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/utils/createBlockStyleButton' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/lib/utils/createInlineStyleButton' {
  declare module.exports: any;
}

declare module 'draft-js-buttons/postcss.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-buttons/lib/components/AlignBlockCenterButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/AlignBlockCenterButton/index'>;
}
declare module 'draft-js-buttons/lib/components/AlignBlockDefaultButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/AlignBlockDefaultButton/index'>;
}
declare module 'draft-js-buttons/lib/components/AlignBlockLeftButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/AlignBlockLeftButton/index'>;
}
declare module 'draft-js-buttons/lib/components/AlignBlockRightButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/AlignBlockRightButton/index'>;
}
declare module 'draft-js-buttons/lib/components/BlockquoteButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/BlockquoteButton/index'>;
}
declare module 'draft-js-buttons/lib/components/BoldButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/BoldButton/index'>;
}
declare module 'draft-js-buttons/lib/components/CodeBlockButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/CodeBlockButton/index'>;
}
declare module 'draft-js-buttons/lib/components/CodeButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/CodeButton/index'>;
}
declare module 'draft-js-buttons/lib/components/HeadlineOneButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/HeadlineOneButton/index'>;
}
declare module 'draft-js-buttons/lib/components/HeadlineThreeButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/HeadlineThreeButton/index'>;
}
declare module 'draft-js-buttons/lib/components/HeadlineTwoButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/HeadlineTwoButton/index'>;
}
declare module 'draft-js-buttons/lib/components/ItalicButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/ItalicButton/index'>;
}
declare module 'draft-js-buttons/lib/components/OrderedListButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/OrderedListButton/index'>;
}
declare module 'draft-js-buttons/lib/components/SubButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/SubButton/index'>;
}
declare module 'draft-js-buttons/lib/components/SupButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/SupButton/index'>;
}
declare module 'draft-js-buttons/lib/components/UnderlineButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/UnderlineButton/index'>;
}
declare module 'draft-js-buttons/lib/components/UnorderedListButton/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/components/UnorderedListButton/index'>;
}
declare module 'draft-js-buttons/lib/index.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/index'>;
}
declare module 'draft-js-buttons/lib/utils/createBlockAlignmentButton.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/utils/createBlockAlignmentButton'>;
}
declare module 'draft-js-buttons/lib/utils/createBlockStyleButton.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/utils/createBlockStyleButton'>;
}
declare module 'draft-js-buttons/lib/utils/createInlineStyleButton.js' {
  declare module.exports: $Exports<'draft-js-buttons/lib/utils/createInlineStyleButton'>;
}
declare module 'draft-js-buttons/postcss.config.js' {
  declare module.exports: $Exports<'draft-js-buttons/postcss.config'>;
}
