// flow-typed signature: 2cd6da2a1d8913f404a3079fb6f17d9b
// flow-typed version: <<STUB>>/draft-js-toolbar-link-plugin_v1.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-toolbar-link-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-toolbar-link-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-toolbar-link-plugin/lib/component/link-commit-button' {
  declare module.exports: any;
}

declare module 'draft-js-toolbar-link-plugin/lib/component/link-remove-button' {
  declare module.exports: any;
}

declare module 'draft-js-toolbar-link-plugin/lib/component/link-sub-menu' {
  declare module.exports: any;
}

declare module 'draft-js-toolbar-link-plugin/lib/component/link-trigger-button' {
  declare module.exports: any;
}

declare module 'draft-js-toolbar-link-plugin/lib/component/link-url-input' {
  declare module.exports: any;
}

declare module 'draft-js-toolbar-link-plugin/lib/component/link' {
  declare module.exports: any;
}

declare module 'draft-js-toolbar-link-plugin/lib/component/styled' {
  declare module.exports: any;
}

declare module 'draft-js-toolbar-link-plugin/lib/component/svg/commit' {
  declare module.exports: any;
}

declare module 'draft-js-toolbar-link-plugin/lib/component/svg/link' {
  declare module.exports: any;
}

declare module 'draft-js-toolbar-link-plugin/lib/component/svg/remove' {
  declare module.exports: any;
}

declare module 'draft-js-toolbar-link-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-toolbar-link-plugin/lib/util/link-action-button-creator' {
  declare module.exports: any;
}

declare module 'draft-js-toolbar-link-plugin/lib/util/link-entity-util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-toolbar-link-plugin/lib/component/link-commit-button.js' {
  declare module.exports: $Exports<'draft-js-toolbar-link-plugin/lib/component/link-commit-button'>;
}
declare module 'draft-js-toolbar-link-plugin/lib/component/link-remove-button.js' {
  declare module.exports: $Exports<'draft-js-toolbar-link-plugin/lib/component/link-remove-button'>;
}
declare module 'draft-js-toolbar-link-plugin/lib/component/link-sub-menu.js' {
  declare module.exports: $Exports<'draft-js-toolbar-link-plugin/lib/component/link-sub-menu'>;
}
declare module 'draft-js-toolbar-link-plugin/lib/component/link-trigger-button.js' {
  declare module.exports: $Exports<'draft-js-toolbar-link-plugin/lib/component/link-trigger-button'>;
}
declare module 'draft-js-toolbar-link-plugin/lib/component/link-url-input.js' {
  declare module.exports: $Exports<'draft-js-toolbar-link-plugin/lib/component/link-url-input'>;
}
declare module 'draft-js-toolbar-link-plugin/lib/component/link.js' {
  declare module.exports: $Exports<'draft-js-toolbar-link-plugin/lib/component/link'>;
}
declare module 'draft-js-toolbar-link-plugin/lib/component/styled.js' {
  declare module.exports: $Exports<'draft-js-toolbar-link-plugin/lib/component/styled'>;
}
declare module 'draft-js-toolbar-link-plugin/lib/component/svg/commit.js' {
  declare module.exports: $Exports<'draft-js-toolbar-link-plugin/lib/component/svg/commit'>;
}
declare module 'draft-js-toolbar-link-plugin/lib/component/svg/link.js' {
  declare module.exports: $Exports<'draft-js-toolbar-link-plugin/lib/component/svg/link'>;
}
declare module 'draft-js-toolbar-link-plugin/lib/component/svg/remove.js' {
  declare module.exports: $Exports<'draft-js-toolbar-link-plugin/lib/component/svg/remove'>;
}
declare module 'draft-js-toolbar-link-plugin/lib/index.js' {
  declare module.exports: $Exports<'draft-js-toolbar-link-plugin/lib/index'>;
}
declare module 'draft-js-toolbar-link-plugin/lib/util/link-action-button-creator.js' {
  declare module.exports: $Exports<'draft-js-toolbar-link-plugin/lib/util/link-action-button-creator'>;
}
declare module 'draft-js-toolbar-link-plugin/lib/util/link-entity-util.js' {
  declare module.exports: $Exports<'draft-js-toolbar-link-plugin/lib/util/link-entity-util'>;
}
