// flow-typed signature: 8daf3c8625abf84715324747d08a5f4c
// flow-typed version: <<STUB>>/draft-js-undo-plugin_v2.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-undo-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-undo-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-undo-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-undo-plugin/lib/RedoButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-undo-plugin/lib/UndoButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-undo-plugin/postcss.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-undo-plugin/lib/index.js' {
  declare module.exports: $Exports<'draft-js-undo-plugin/lib/index'>;
}
declare module 'draft-js-undo-plugin/lib/RedoButton/index.js' {
  declare module.exports: $Exports<'draft-js-undo-plugin/lib/RedoButton/index'>;
}
declare module 'draft-js-undo-plugin/lib/UndoButton/index.js' {
  declare module.exports: $Exports<'draft-js-undo-plugin/lib/UndoButton/index'>;
}
declare module 'draft-js-undo-plugin/postcss.config.js' {
  declare module.exports: $Exports<'draft-js-undo-plugin/postcss.config'>;
}
