// flow-typed signature: 0676c7bd36ff3c7162a3fddb1fccc1b2
// flow-typed version: <<STUB>>/redux-form_v5.3.6/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-form/dist/redux-form' {
  declare module.exports: any;
}

declare module 'redux-form/dist/redux-form.min' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/actions.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/asyncValidation.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/bindActionData.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/createReduxForm.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/fieldValue.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/getDisplayName.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/getValues.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/getValuesFromState.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/handleSubmit.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/initializeState.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/isPristine.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/isValid.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/mapValues.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/read.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/readField.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/readFields.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/removeField.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/resetState.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/setErrors.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/setup' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/updateField.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/wrapMapDispatchToProps.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/wrapMapStateToProps.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/write.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/actions' {
  declare module.exports: any;
}

declare module 'redux-form/lib/actionTypes' {
  declare module.exports: any;
}

declare module 'redux-form/lib/asyncValidation' {
  declare module.exports: any;
}

declare module 'redux-form/lib/bindActionData' {
  declare module.exports: any;
}

declare module 'redux-form/lib/createAll' {
  declare module.exports: any;
}

declare module 'redux-form/lib/createHigherOrderComponent' {
  declare module.exports: any;
}

declare module 'redux-form/lib/createInitialState' {
  declare module.exports: any;
}

declare module 'redux-form/lib/createPropTypes' {
  declare module.exports: any;
}

declare module 'redux-form/lib/createReduxForm' {
  declare module.exports: any;
}

declare module 'redux-form/lib/createReduxFormConnector' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/__tests__/createOnBlur.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/__tests__/createOnChange.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/__tests__/createOnDragStart.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/__tests__/createOnDrop.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/__tests__/createOnFocus.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/__tests__/getValue.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/__tests__/isEvent.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/__tests__/silenceEvent.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/__tests__/silenceEvents.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/createOnBlur' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/createOnChange' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/createOnDragStart' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/createOnDrop' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/createOnFocus' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/getValue' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/isEvent' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/silenceEvent' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/silenceEvents' {
  declare module.exports: any;
}

declare module 'redux-form/lib/fieldValue' {
  declare module.exports: any;
}

declare module 'redux-form/lib/getDisplayName' {
  declare module.exports: any;
}

declare module 'redux-form/lib/getValues' {
  declare module.exports: any;
}

declare module 'redux-form/lib/getValuesFromState' {
  declare module.exports: any;
}

declare module 'redux-form/lib/handleSubmit' {
  declare module.exports: any;
}

declare module 'redux-form/lib/index' {
  declare module.exports: any;
}

declare module 'redux-form/lib/initializeState' {
  declare module.exports: any;
}

declare module 'redux-form/lib/isChecked' {
  declare module.exports: any;
}

declare module 'redux-form/lib/isPristine' {
  declare module.exports: any;
}

declare module 'redux-form/lib/isValid' {
  declare module.exports: any;
}

declare module 'redux-form/lib/mapValues' {
  declare module.exports: any;
}

declare module 'redux-form/lib/native' {
  declare module.exports: any;
}

declare module 'redux-form/lib/normalizeFields' {
  declare module.exports: any;
}

declare module 'redux-form/lib/read' {
  declare module.exports: any;
}

declare module 'redux-form/lib/readField' {
  declare module.exports: any;
}

declare module 'redux-form/lib/readFields' {
  declare module.exports: any;
}

declare module 'redux-form/lib/reducer' {
  declare module.exports: any;
}

declare module 'redux-form/lib/removeField' {
  declare module.exports: any;
}

declare module 'redux-form/lib/resetState' {
  declare module.exports: any;
}

declare module 'redux-form/lib/setErrors' {
  declare module.exports: any;
}

declare module 'redux-form/lib/silencePromise' {
  declare module.exports: any;
}

declare module 'redux-form/lib/updateField' {
  declare module.exports: any;
}

declare module 'redux-form/lib/wrapMapDispatchToProps' {
  declare module.exports: any;
}

declare module 'redux-form/lib/wrapMapStateToProps' {
  declare module.exports: any;
}

declare module 'redux-form/lib/write' {
  declare module.exports: any;
}

declare module 'redux-form/native' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/actions.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/asyncValidation.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/bindActionData.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/createReduxForm.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/fieldValue.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/getDisplayName.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/getValues.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/getValuesFromState.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/handleSubmit.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/initializeState.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/isPristine.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/isValid.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/mapValues.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/read.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/readField.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/readFields.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/reducer.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/removeField.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/resetState.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/setErrors.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/setup' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/updateField.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/wrapMapDispatchToProps.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/wrapMapStateToProps.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/__tests__/write.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/actions' {
  declare module.exports: any;
}

declare module 'redux-form/src/actionTypes' {
  declare module.exports: any;
}

declare module 'redux-form/src/asyncValidation' {
  declare module.exports: any;
}

declare module 'redux-form/src/bindActionData' {
  declare module.exports: any;
}

declare module 'redux-form/src/createAll' {
  declare module.exports: any;
}

declare module 'redux-form/src/createHigherOrderComponent' {
  declare module.exports: any;
}

declare module 'redux-form/src/createInitialState' {
  declare module.exports: any;
}

declare module 'redux-form/src/createPropTypes' {
  declare module.exports: any;
}

declare module 'redux-form/src/createReduxForm' {
  declare module.exports: any;
}

declare module 'redux-form/src/createReduxFormConnector' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/__tests__/createOnBlur.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/__tests__/createOnChange.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/__tests__/createOnDragStart.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/__tests__/createOnDrop.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/__tests__/createOnFocus.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/__tests__/getValue.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/__tests__/isEvent.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/__tests__/silenceEvent.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/__tests__/silenceEvents.spec' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/createOnBlur' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/createOnChange' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/createOnDragStart' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/createOnDrop' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/createOnFocus' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/getValue' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/isEvent' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/silenceEvent' {
  declare module.exports: any;
}

declare module 'redux-form/src/events/silenceEvents' {
  declare module.exports: any;
}

declare module 'redux-form/src/fieldValue' {
  declare module.exports: any;
}

declare module 'redux-form/src/getDisplayName' {
  declare module.exports: any;
}

declare module 'redux-form/src/getValues' {
  declare module.exports: any;
}

declare module 'redux-form/src/getValuesFromState' {
  declare module.exports: any;
}

declare module 'redux-form/src/handleSubmit' {
  declare module.exports: any;
}

declare module 'redux-form/src/index' {
  declare module.exports: any;
}

declare module 'redux-form/src/initializeState' {
  declare module.exports: any;
}

declare module 'redux-form/src/isChecked' {
  declare module.exports: any;
}

declare module 'redux-form/src/isPristine' {
  declare module.exports: any;
}

declare module 'redux-form/src/isValid' {
  declare module.exports: any;
}

declare module 'redux-form/src/mapValues' {
  declare module.exports: any;
}

declare module 'redux-form/src/native' {
  declare module.exports: any;
}

declare module 'redux-form/src/normalizeFields' {
  declare module.exports: any;
}

declare module 'redux-form/src/read' {
  declare module.exports: any;
}

declare module 'redux-form/src/readField' {
  declare module.exports: any;
}

declare module 'redux-form/src/readFields' {
  declare module.exports: any;
}

declare module 'redux-form/src/reducer' {
  declare module.exports: any;
}

declare module 'redux-form/src/removeField' {
  declare module.exports: any;
}

declare module 'redux-form/src/resetState' {
  declare module.exports: any;
}

declare module 'redux-form/src/setErrors' {
  declare module.exports: any;
}

declare module 'redux-form/src/silencePromise' {
  declare module.exports: any;
}

declare module 'redux-form/src/updateField' {
  declare module.exports: any;
}

declare module 'redux-form/src/wrapMapDispatchToProps' {
  declare module.exports: any;
}

declare module 'redux-form/src/wrapMapStateToProps' {
  declare module.exports: any;
}

declare module 'redux-form/src/write' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-form/dist/redux-form.js' {
  declare module.exports: $Exports<'redux-form/dist/redux-form'>;
}
declare module 'redux-form/dist/redux-form.min.js' {
  declare module.exports: $Exports<'redux-form/dist/redux-form.min'>;
}
declare module 'redux-form/lib/__tests__/actions.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/actions.spec'>;
}
declare module 'redux-form/lib/__tests__/asyncValidation.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/asyncValidation.spec'>;
}
declare module 'redux-form/lib/__tests__/bindActionData.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/bindActionData.spec'>;
}
declare module 'redux-form/lib/__tests__/createReduxForm.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/createReduxForm.spec'>;
}
declare module 'redux-form/lib/__tests__/fieldValue.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/fieldValue.spec'>;
}
declare module 'redux-form/lib/__tests__/getDisplayName.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/getDisplayName.spec'>;
}
declare module 'redux-form/lib/__tests__/getValues.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/getValues.spec'>;
}
declare module 'redux-form/lib/__tests__/getValuesFromState.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/getValuesFromState.spec'>;
}
declare module 'redux-form/lib/__tests__/handleSubmit.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/handleSubmit.spec'>;
}
declare module 'redux-form/lib/__tests__/initializeState.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/initializeState.spec'>;
}
declare module 'redux-form/lib/__tests__/isPristine.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/isPristine.spec'>;
}
declare module 'redux-form/lib/__tests__/isValid.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/isValid.spec'>;
}
declare module 'redux-form/lib/__tests__/mapValues.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/mapValues.spec'>;
}
declare module 'redux-form/lib/__tests__/read.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/read.spec'>;
}
declare module 'redux-form/lib/__tests__/readField.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/readField.spec'>;
}
declare module 'redux-form/lib/__tests__/readFields.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/readFields.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.spec'>;
}
declare module 'redux-form/lib/__tests__/removeField.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/removeField.spec'>;
}
declare module 'redux-form/lib/__tests__/resetState.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/resetState.spec'>;
}
declare module 'redux-form/lib/__tests__/setErrors.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/setErrors.spec'>;
}
declare module 'redux-form/lib/__tests__/setup.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/setup'>;
}
declare module 'redux-form/lib/__tests__/updateField.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/updateField.spec'>;
}
declare module 'redux-form/lib/__tests__/wrapMapDispatchToProps.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/wrapMapDispatchToProps.spec'>;
}
declare module 'redux-form/lib/__tests__/wrapMapStateToProps.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/wrapMapStateToProps.spec'>;
}
declare module 'redux-form/lib/__tests__/write.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/write.spec'>;
}
declare module 'redux-form/lib/actions.js' {
  declare module.exports: $Exports<'redux-form/lib/actions'>;
}
declare module 'redux-form/lib/actionTypes.js' {
  declare module.exports: $Exports<'redux-form/lib/actionTypes'>;
}
declare module 'redux-form/lib/asyncValidation.js' {
  declare module.exports: $Exports<'redux-form/lib/asyncValidation'>;
}
declare module 'redux-form/lib/bindActionData.js' {
  declare module.exports: $Exports<'redux-form/lib/bindActionData'>;
}
declare module 'redux-form/lib/createAll.js' {
  declare module.exports: $Exports<'redux-form/lib/createAll'>;
}
declare module 'redux-form/lib/createHigherOrderComponent.js' {
  declare module.exports: $Exports<'redux-form/lib/createHigherOrderComponent'>;
}
declare module 'redux-form/lib/createInitialState.js' {
  declare module.exports: $Exports<'redux-form/lib/createInitialState'>;
}
declare module 'redux-form/lib/createPropTypes.js' {
  declare module.exports: $Exports<'redux-form/lib/createPropTypes'>;
}
declare module 'redux-form/lib/createReduxForm.js' {
  declare module.exports: $Exports<'redux-form/lib/createReduxForm'>;
}
declare module 'redux-form/lib/createReduxFormConnector.js' {
  declare module.exports: $Exports<'redux-form/lib/createReduxFormConnector'>;
}
declare module 'redux-form/lib/events/__tests__/createOnBlur.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/events/__tests__/createOnBlur.spec'>;
}
declare module 'redux-form/lib/events/__tests__/createOnChange.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/events/__tests__/createOnChange.spec'>;
}
declare module 'redux-form/lib/events/__tests__/createOnDragStart.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/events/__tests__/createOnDragStart.spec'>;
}
declare module 'redux-form/lib/events/__tests__/createOnDrop.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/events/__tests__/createOnDrop.spec'>;
}
declare module 'redux-form/lib/events/__tests__/createOnFocus.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/events/__tests__/createOnFocus.spec'>;
}
declare module 'redux-form/lib/events/__tests__/getValue.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/events/__tests__/getValue.spec'>;
}
declare module 'redux-form/lib/events/__tests__/isEvent.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/events/__tests__/isEvent.spec'>;
}
declare module 'redux-form/lib/events/__tests__/silenceEvent.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/events/__tests__/silenceEvent.spec'>;
}
declare module 'redux-form/lib/events/__tests__/silenceEvents.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/events/__tests__/silenceEvents.spec'>;
}
declare module 'redux-form/lib/events/createOnBlur.js' {
  declare module.exports: $Exports<'redux-form/lib/events/createOnBlur'>;
}
declare module 'redux-form/lib/events/createOnChange.js' {
  declare module.exports: $Exports<'redux-form/lib/events/createOnChange'>;
}
declare module 'redux-form/lib/events/createOnDragStart.js' {
  declare module.exports: $Exports<'redux-form/lib/events/createOnDragStart'>;
}
declare module 'redux-form/lib/events/createOnDrop.js' {
  declare module.exports: $Exports<'redux-form/lib/events/createOnDrop'>;
}
declare module 'redux-form/lib/events/createOnFocus.js' {
  declare module.exports: $Exports<'redux-form/lib/events/createOnFocus'>;
}
declare module 'redux-form/lib/events/getValue.js' {
  declare module.exports: $Exports<'redux-form/lib/events/getValue'>;
}
declare module 'redux-form/lib/events/isEvent.js' {
  declare module.exports: $Exports<'redux-form/lib/events/isEvent'>;
}
declare module 'redux-form/lib/events/silenceEvent.js' {
  declare module.exports: $Exports<'redux-form/lib/events/silenceEvent'>;
}
declare module 'redux-form/lib/events/silenceEvents.js' {
  declare module.exports: $Exports<'redux-form/lib/events/silenceEvents'>;
}
declare module 'redux-form/lib/fieldValue.js' {
  declare module.exports: $Exports<'redux-form/lib/fieldValue'>;
}
declare module 'redux-form/lib/getDisplayName.js' {
  declare module.exports: $Exports<'redux-form/lib/getDisplayName'>;
}
declare module 'redux-form/lib/getValues.js' {
  declare module.exports: $Exports<'redux-form/lib/getValues'>;
}
declare module 'redux-form/lib/getValuesFromState.js' {
  declare module.exports: $Exports<'redux-form/lib/getValuesFromState'>;
}
declare module 'redux-form/lib/handleSubmit.js' {
  declare module.exports: $Exports<'redux-form/lib/handleSubmit'>;
}
declare module 'redux-form/lib/index.js' {
  declare module.exports: $Exports<'redux-form/lib/index'>;
}
declare module 'redux-form/lib/initializeState.js' {
  declare module.exports: $Exports<'redux-form/lib/initializeState'>;
}
declare module 'redux-form/lib/isChecked.js' {
  declare module.exports: $Exports<'redux-form/lib/isChecked'>;
}
declare module 'redux-form/lib/isPristine.js' {
  declare module.exports: $Exports<'redux-form/lib/isPristine'>;
}
declare module 'redux-form/lib/isValid.js' {
  declare module.exports: $Exports<'redux-form/lib/isValid'>;
}
declare module 'redux-form/lib/mapValues.js' {
  declare module.exports: $Exports<'redux-form/lib/mapValues'>;
}
declare module 'redux-form/lib/native.js' {
  declare module.exports: $Exports<'redux-form/lib/native'>;
}
declare module 'redux-form/lib/normalizeFields.js' {
  declare module.exports: $Exports<'redux-form/lib/normalizeFields'>;
}
declare module 'redux-form/lib/read.js' {
  declare module.exports: $Exports<'redux-form/lib/read'>;
}
declare module 'redux-form/lib/readField.js' {
  declare module.exports: $Exports<'redux-form/lib/readField'>;
}
declare module 'redux-form/lib/readFields.js' {
  declare module.exports: $Exports<'redux-form/lib/readFields'>;
}
declare module 'redux-form/lib/reducer.js' {
  declare module.exports: $Exports<'redux-form/lib/reducer'>;
}
declare module 'redux-form/lib/removeField.js' {
  declare module.exports: $Exports<'redux-form/lib/removeField'>;
}
declare module 'redux-form/lib/resetState.js' {
  declare module.exports: $Exports<'redux-form/lib/resetState'>;
}
declare module 'redux-form/lib/setErrors.js' {
  declare module.exports: $Exports<'redux-form/lib/setErrors'>;
}
declare module 'redux-form/lib/silencePromise.js' {
  declare module.exports: $Exports<'redux-form/lib/silencePromise'>;
}
declare module 'redux-form/lib/updateField.js' {
  declare module.exports: $Exports<'redux-form/lib/updateField'>;
}
declare module 'redux-form/lib/wrapMapDispatchToProps.js' {
  declare module.exports: $Exports<'redux-form/lib/wrapMapDispatchToProps'>;
}
declare module 'redux-form/lib/wrapMapStateToProps.js' {
  declare module.exports: $Exports<'redux-form/lib/wrapMapStateToProps'>;
}
declare module 'redux-form/lib/write.js' {
  declare module.exports: $Exports<'redux-form/lib/write'>;
}
declare module 'redux-form/native.js' {
  declare module.exports: $Exports<'redux-form/native'>;
}
declare module 'redux-form/src/__tests__/actions.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/actions.spec'>;
}
declare module 'redux-form/src/__tests__/asyncValidation.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/asyncValidation.spec'>;
}
declare module 'redux-form/src/__tests__/bindActionData.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/bindActionData.spec'>;
}
declare module 'redux-form/src/__tests__/createReduxForm.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/createReduxForm.spec'>;
}
declare module 'redux-form/src/__tests__/fieldValue.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/fieldValue.spec'>;
}
declare module 'redux-form/src/__tests__/getDisplayName.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/getDisplayName.spec'>;
}
declare module 'redux-form/src/__tests__/getValues.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/getValues.spec'>;
}
declare module 'redux-form/src/__tests__/getValuesFromState.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/getValuesFromState.spec'>;
}
declare module 'redux-form/src/__tests__/handleSubmit.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/handleSubmit.spec'>;
}
declare module 'redux-form/src/__tests__/initializeState.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/initializeState.spec'>;
}
declare module 'redux-form/src/__tests__/isPristine.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/isPristine.spec'>;
}
declare module 'redux-form/src/__tests__/isValid.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/isValid.spec'>;
}
declare module 'redux-form/src/__tests__/mapValues.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/mapValues.spec'>;
}
declare module 'redux-form/src/__tests__/read.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/read.spec'>;
}
declare module 'redux-form/src/__tests__/readField.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/readField.spec'>;
}
declare module 'redux-form/src/__tests__/readFields.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/readFields.spec'>;
}
declare module 'redux-form/src/__tests__/reducer.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/reducer.spec'>;
}
declare module 'redux-form/src/__tests__/removeField.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/removeField.spec'>;
}
declare module 'redux-form/src/__tests__/resetState.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/resetState.spec'>;
}
declare module 'redux-form/src/__tests__/setErrors.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/setErrors.spec'>;
}
declare module 'redux-form/src/__tests__/setup.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/setup'>;
}
declare module 'redux-form/src/__tests__/updateField.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/updateField.spec'>;
}
declare module 'redux-form/src/__tests__/wrapMapDispatchToProps.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/wrapMapDispatchToProps.spec'>;
}
declare module 'redux-form/src/__tests__/wrapMapStateToProps.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/wrapMapStateToProps.spec'>;
}
declare module 'redux-form/src/__tests__/write.spec.js' {
  declare module.exports: $Exports<'redux-form/src/__tests__/write.spec'>;
}
declare module 'redux-form/src/actions.js' {
  declare module.exports: $Exports<'redux-form/src/actions'>;
}
declare module 'redux-form/src/actionTypes.js' {
  declare module.exports: $Exports<'redux-form/src/actionTypes'>;
}
declare module 'redux-form/src/asyncValidation.js' {
  declare module.exports: $Exports<'redux-form/src/asyncValidation'>;
}
declare module 'redux-form/src/bindActionData.js' {
  declare module.exports: $Exports<'redux-form/src/bindActionData'>;
}
declare module 'redux-form/src/createAll.js' {
  declare module.exports: $Exports<'redux-form/src/createAll'>;
}
declare module 'redux-form/src/createHigherOrderComponent.js' {
  declare module.exports: $Exports<'redux-form/src/createHigherOrderComponent'>;
}
declare module 'redux-form/src/createInitialState.js' {
  declare module.exports: $Exports<'redux-form/src/createInitialState'>;
}
declare module 'redux-form/src/createPropTypes.js' {
  declare module.exports: $Exports<'redux-form/src/createPropTypes'>;
}
declare module 'redux-form/src/createReduxForm.js' {
  declare module.exports: $Exports<'redux-form/src/createReduxForm'>;
}
declare module 'redux-form/src/createReduxFormConnector.js' {
  declare module.exports: $Exports<'redux-form/src/createReduxFormConnector'>;
}
declare module 'redux-form/src/events/__tests__/createOnBlur.spec.js' {
  declare module.exports: $Exports<'redux-form/src/events/__tests__/createOnBlur.spec'>;
}
declare module 'redux-form/src/events/__tests__/createOnChange.spec.js' {
  declare module.exports: $Exports<'redux-form/src/events/__tests__/createOnChange.spec'>;
}
declare module 'redux-form/src/events/__tests__/createOnDragStart.spec.js' {
  declare module.exports: $Exports<'redux-form/src/events/__tests__/createOnDragStart.spec'>;
}
declare module 'redux-form/src/events/__tests__/createOnDrop.spec.js' {
  declare module.exports: $Exports<'redux-form/src/events/__tests__/createOnDrop.spec'>;
}
declare module 'redux-form/src/events/__tests__/createOnFocus.spec.js' {
  declare module.exports: $Exports<'redux-form/src/events/__tests__/createOnFocus.spec'>;
}
declare module 'redux-form/src/events/__tests__/getValue.spec.js' {
  declare module.exports: $Exports<'redux-form/src/events/__tests__/getValue.spec'>;
}
declare module 'redux-form/src/events/__tests__/isEvent.spec.js' {
  declare module.exports: $Exports<'redux-form/src/events/__tests__/isEvent.spec'>;
}
declare module 'redux-form/src/events/__tests__/silenceEvent.spec.js' {
  declare module.exports: $Exports<'redux-form/src/events/__tests__/silenceEvent.spec'>;
}
declare module 'redux-form/src/events/__tests__/silenceEvents.spec.js' {
  declare module.exports: $Exports<'redux-form/src/events/__tests__/silenceEvents.spec'>;
}
declare module 'redux-form/src/events/createOnBlur.js' {
  declare module.exports: $Exports<'redux-form/src/events/createOnBlur'>;
}
declare module 'redux-form/src/events/createOnChange.js' {
  declare module.exports: $Exports<'redux-form/src/events/createOnChange'>;
}
declare module 'redux-form/src/events/createOnDragStart.js' {
  declare module.exports: $Exports<'redux-form/src/events/createOnDragStart'>;
}
declare module 'redux-form/src/events/createOnDrop.js' {
  declare module.exports: $Exports<'redux-form/src/events/createOnDrop'>;
}
declare module 'redux-form/src/events/createOnFocus.js' {
  declare module.exports: $Exports<'redux-form/src/events/createOnFocus'>;
}
declare module 'redux-form/src/events/getValue.js' {
  declare module.exports: $Exports<'redux-form/src/events/getValue'>;
}
declare module 'redux-form/src/events/isEvent.js' {
  declare module.exports: $Exports<'redux-form/src/events/isEvent'>;
}
declare module 'redux-form/src/events/silenceEvent.js' {
  declare module.exports: $Exports<'redux-form/src/events/silenceEvent'>;
}
declare module 'redux-form/src/events/silenceEvents.js' {
  declare module.exports: $Exports<'redux-form/src/events/silenceEvents'>;
}
declare module 'redux-form/src/fieldValue.js' {
  declare module.exports: $Exports<'redux-form/src/fieldValue'>;
}
declare module 'redux-form/src/getDisplayName.js' {
  declare module.exports: $Exports<'redux-form/src/getDisplayName'>;
}
declare module 'redux-form/src/getValues.js' {
  declare module.exports: $Exports<'redux-form/src/getValues'>;
}
declare module 'redux-form/src/getValuesFromState.js' {
  declare module.exports: $Exports<'redux-form/src/getValuesFromState'>;
}
declare module 'redux-form/src/handleSubmit.js' {
  declare module.exports: $Exports<'redux-form/src/handleSubmit'>;
}
declare module 'redux-form/src/index.js' {
  declare module.exports: $Exports<'redux-form/src/index'>;
}
declare module 'redux-form/src/initializeState.js' {
  declare module.exports: $Exports<'redux-form/src/initializeState'>;
}
declare module 'redux-form/src/isChecked.js' {
  declare module.exports: $Exports<'redux-form/src/isChecked'>;
}
declare module 'redux-form/src/isPristine.js' {
  declare module.exports: $Exports<'redux-form/src/isPristine'>;
}
declare module 'redux-form/src/isValid.js' {
  declare module.exports: $Exports<'redux-form/src/isValid'>;
}
declare module 'redux-form/src/mapValues.js' {
  declare module.exports: $Exports<'redux-form/src/mapValues'>;
}
declare module 'redux-form/src/native.js' {
  declare module.exports: $Exports<'redux-form/src/native'>;
}
declare module 'redux-form/src/normalizeFields.js' {
  declare module.exports: $Exports<'redux-form/src/normalizeFields'>;
}
declare module 'redux-form/src/read.js' {
  declare module.exports: $Exports<'redux-form/src/read'>;
}
declare module 'redux-form/src/readField.js' {
  declare module.exports: $Exports<'redux-form/src/readField'>;
}
declare module 'redux-form/src/readFields.js' {
  declare module.exports: $Exports<'redux-form/src/readFields'>;
}
declare module 'redux-form/src/reducer.js' {
  declare module.exports: $Exports<'redux-form/src/reducer'>;
}
declare module 'redux-form/src/removeField.js' {
  declare module.exports: $Exports<'redux-form/src/removeField'>;
}
declare module 'redux-form/src/resetState.js' {
  declare module.exports: $Exports<'redux-form/src/resetState'>;
}
declare module 'redux-form/src/setErrors.js' {
  declare module.exports: $Exports<'redux-form/src/setErrors'>;
}
declare module 'redux-form/src/silencePromise.js' {
  declare module.exports: $Exports<'redux-form/src/silencePromise'>;
}
declare module 'redux-form/src/updateField.js' {
  declare module.exports: $Exports<'redux-form/src/updateField'>;
}
declare module 'redux-form/src/wrapMapDispatchToProps.js' {
  declare module.exports: $Exports<'redux-form/src/wrapMapDispatchToProps'>;
}
declare module 'redux-form/src/wrapMapStateToProps.js' {
  declare module.exports: $Exports<'redux-form/src/wrapMapStateToProps'>;
}
declare module 'redux-form/src/write.js' {
  declare module.exports: $Exports<'redux-form/src/write'>;
}
