// export your constants
const dsctypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  FETCH_USER_REQUEST: "FETCH_USER_REQUEST",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_FAILURE: "FETCH_USER_FAILURE",
  FETCH_ROLE_REQUEST: "FETCH_ROLE_REQUEST",
  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAILURE: "FETCH_ROLE_FAILURE",
  FETCH_NON_AUTH_ROLE_REQUEST: "FETCH_NON_AUTH_ROLE_REQUEST",
  FETCH_NON_AUTH_ROLE_SUCCESS: "FETCH_NON_AUTH_ROLE_SUCCESS",
  FETCH_NON_AUTH_ROLE_FAILURE: "FETCH_NON_AUTH_ROLE_FAILURE",
  FETCH_PERMISSION_REQUEST: "FETCH_PERMISSION_REQUEST",
  FETCH_PERMISSION_SUCCESS: "FETCH_PERMISSION_SUCCESS",
  FETCH_PERMISSION_FAILURE: "FETCH_PERMISSION_FAILURE",
  CREATE_PAGE: "CREATE_PAGE",
  READ_PAGE: "READ_PAGE",
  EDIT_PAGE: "EDIT_PAGE",
  SAVE_PAGE_REQUEST: "SAVE_PAGE_REQUEST",
  SAVE_PAGE_SUCCESS: "SAVE_PAGE_SUCCESS",
  SAVE_PAGE_FAILURE: "SAVE_PAGE_FAILURE",
  SAVE_INLINE_PAGE_SUCCESS: "SAVE_INLINE_PAGE_SUCCESS",
  FETCH_PAGE_REQUEST: "FETCH_PAGE_REQUEST",
  FETCH_PAGE_SUCCESS: "FETCH_PAGE_SUCCESS",
  FETCH_PAGE_FAILURE: "FETCH_PAGE_FAILURE",
  DELETE_PAGE: "DELETE_PAGE",
  AVAILABILITY_FETCH_REQUEST: "AVAILABILITY_FETCH_REQUEST",
  AVAILABILITY_FETCH_SUCCESS: "AVAILABILITY_FETCH_SUCCESS",
  AVAILABILITY_FETCH_FAILURE: "AVAILABILITY_FETCH_FAILURE",
}

const NAMESPACE = "dsc"

export { dsctypes, NAMESPACE }
