// export your constants
const types = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    ADD_SHIPPING: 'ADD_SHIPPING',
    ADD_PAYMENT: 'ADD_PAYMENT',
    SUBMIT_ORDER: 'SUBMIT_ORDER'
}

export default types
