// export your constants
const types = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    ADD_SHIPPING_INFO: 'ADD_SHIPPING_INFO',
    ADD_PAYMENT_INFO: 'ADD_PAYMENT_INFO'
}

export default types
