// export your constants
const types = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    ADD_SHIPPING: 'ADD_SHIPPING',
    ADD_PAYMENT: 'ADD_PAYMENT',
    SAME_AS_SHIPPING: 'SAME_AS_SHIPPING',
    SUBMIT_REQUEST: 'SUBMIT_REQUEST',
    SUBMIT_SUCCESS: 'SUBMIT_SUCCESS',
    SUBMIT_FAILURE: 'SUBMIT_FAILURE',
    CREATE_PAGE: 'CREATE_PAGE',
    READ_PAGE: 'READ_PAGE',
    EDIT_PAGE: 'EDIT_PAGE',
    SAVE_PAGE_REQUEST: 'SAVE_PAGE_REQUEST',
    SAVE_PAGE_SUCCESS: 'SAVE_PAGE_SUCCESS',
    SAVE_PAGE_FAILURE: 'SAVE_PAGE_FAILURE',
    FETCH_PAGE_REQUEST: 'FETCH_PAGE_REQUEST',
    FETCH_PAGE_SUCCESS: 'FETCH_PAGE_SUCCESS',
    FETCH_PAGE_FAILURE: 'FETCH_PAGE_FAILURE',
    DELETE_PAGE: 'DELETE_PAGE',
    AVAILABILITY_FETCH_REQUEST: 'AVAILABILITY_FETCH_REQUEST',
    AVAILABILITY_FETCH_SUCCESS: 'AVAILABILITY_FETCH_SUCCESS',
    AVAILABILITY_FETCH_FAILURE: 'AVAILABILITY_FETCH_FAILURE',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    STRAINS_FETCH_REQUEST: 'STRAINS_FETCH_REQUEST',
    STRAINS_FETCH_SUCCESS: 'STRAINS_FETCH_SUCCESS',
    STRAINS_FETCH_FAILURE: 'STRAINS_FETCH_FAILURE'
}

export const fees = {
    STRAIN_FEE: '$30.00',
    PLASMID_FEE: '$15.00',
    OTHER_FEE: '$40.00'
}

export default types
