// flow-typed signature: d52568e98fab0bee56fb6838abc18284
// flow-typed version: <<STUB>>/@apollo/react-hooks_v3.1.3/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@apollo/react-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@apollo/react-hooks" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@apollo/react-hooks/lib/data/MutationData" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/data/OperationData" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/data/QueryData" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/data/SubscriptionData" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/index" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/react-hooks.cjs" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/react-hooks.cjs.min" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/react-hooks.esm" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/react-hooks.umd" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/ssr/RenderPromises" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/types" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/useApolloClient" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/useLazyQuery" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/useMutation" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/useQuery" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/useSubscription" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/utils/useBaseQuery" {
  declare module.exports: any
}

declare module "@apollo/react-hooks/lib/utils/useDeepMemo" {
  declare module.exports: any
}

// Filename aliases
declare module "@apollo/react-hooks/lib/data/MutationData.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/data/MutationData">
}
declare module "@apollo/react-hooks/lib/data/OperationData.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/data/OperationData">
}
declare module "@apollo/react-hooks/lib/data/QueryData.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/data/QueryData">
}
declare module "@apollo/react-hooks/lib/data/SubscriptionData.js" {
  declare module.exports: $Exports<
    "@apollo/react-hooks/lib/data/SubscriptionData",
  >
}
declare module "@apollo/react-hooks/lib/index.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/index">
}
declare module "@apollo/react-hooks/lib/react-hooks.cjs.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/react-hooks.cjs">
}
declare module "@apollo/react-hooks/lib/react-hooks.cjs.min.js" {
  declare module.exports: $Exports<
    "@apollo/react-hooks/lib/react-hooks.cjs.min",
  >
}
declare module "@apollo/react-hooks/lib/react-hooks.esm.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/react-hooks.esm">
}
declare module "@apollo/react-hooks/lib/react-hooks.umd.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/react-hooks.umd">
}
declare module "@apollo/react-hooks/lib/ssr/RenderPromises.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/ssr/RenderPromises">
}
declare module "@apollo/react-hooks/lib/types.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/types">
}
declare module "@apollo/react-hooks/lib/useApolloClient.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/useApolloClient">
}
declare module "@apollo/react-hooks/lib/useLazyQuery.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/useLazyQuery">
}
declare module "@apollo/react-hooks/lib/useMutation.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/useMutation">
}
declare module "@apollo/react-hooks/lib/useQuery.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/useQuery">
}
declare module "@apollo/react-hooks/lib/useSubscription.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/useSubscription">
}
declare module "@apollo/react-hooks/lib/utils/useBaseQuery.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/utils/useBaseQuery">
}
declare module "@apollo/react-hooks/lib/utils/useDeepMemo.js" {
  declare module.exports: $Exports<"@apollo/react-hooks/lib/utils/useDeepMemo">
}
