// flow-typed signature: ca4f94ea2a05a5f81b673ad10bcbddf5
// flow-typed version: <<STUB>>/@material-ui/core/InputBase_vx.x.x/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/InputBase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@material-ui/core/InputBase" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@material-ui/core/InputBase/InputBase" {
  declare module.exports: any
}

declare module "@material-ui/core/InputBase/utils" {
  declare module.exports: any
}

// Filename aliases
declare module "@material-ui/core/InputBase/index" {
  declare module.exports: $Exports<"@material-ui/core/InputBase">
}
declare module "@material-ui/core/InputBase/index.js" {
  declare module.exports: $Exports<"@material-ui/core/InputBase">
}
declare module "@material-ui/core/InputBase/InputBase.js" {
  declare module.exports: $Exports<"@material-ui/core/InputBase/InputBase">
}
declare module "@material-ui/core/InputBase/utils.js" {
  declare module.exports: $Exports<"@material-ui/core/InputBase/utils">
}
