// flow-typed signature: 6198bd19dff41fdc7d48e7e2235934f7
// flow-typed version: <<STUB>>/@material-ui/core/OutlinedInput_vx.x.x/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/OutlinedInput'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@material-ui/core/OutlinedInput" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@material-ui/core/OutlinedInput/NotchedOutline" {
  declare module.exports: any
}

declare module "@material-ui/core/OutlinedInput/OutlinedInput" {
  declare module.exports: any
}

// Filename aliases
declare module "@material-ui/core/OutlinedInput/index" {
  declare module.exports: $Exports<"@material-ui/core/OutlinedInput">
}
declare module "@material-ui/core/OutlinedInput/index.js" {
  declare module.exports: $Exports<"@material-ui/core/OutlinedInput">
}
declare module "@material-ui/core/OutlinedInput/NotchedOutline.js" {
  declare module.exports: $Exports<
    "@material-ui/core/OutlinedInput/NotchedOutline",
  >
}
declare module "@material-ui/core/OutlinedInput/OutlinedInput.js" {
  declare module.exports: $Exports<
    "@material-ui/core/OutlinedInput/OutlinedInput",
  >
}
