name: Node CI Develop
on: pull_request
jobs:
  lighthouse:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: audit url using lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://eric.dictybase.dev/stockcenter
          temporaryPublicStorage: true
      - name: Save results
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: ".lighthouseci"
