name: Lighthouse CI
on: pull_request
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-18.04
    steps:
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: check out code
        uses: actions/checkout@v1
      - name: set up app
        run: |
          cp package.json package-dev.json && rm package.json
          jq 'del(.homepage)' package-dev.json > package.json && rm package-dev.json
          mv src/common/utils/clientConfig.sample.ts src/common/utils/clientConfig.ts
      - name: run build
        run: |
          npm ci
          npm i -g serve
          npm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
