name: Cypress Test
on: pull_request
jobs:
  # test:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: set up node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 10.x
  #     - name: check out code
  #       uses: actions/checkout@v1
  #     - name: cache npm dependencies
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-
  #     - name: npm install and test
  #       run: |
  #         mv src/utils/clientConfig.sample.js src/utils/clientConfig.js
  #         npm ci
  #         npm test -- --coverage
  #       env:
  #         CI: true
  #     - name: upload coverage to codecov
  #       uses: codecov/codecov-action@v1.0.2
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}
  # build:
  #   needs: test
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: set up node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 10.x
  #     - name: check out code
  #       uses: actions/checkout@v1
  #     - name: build ericdev docker image
  #       run: docker build -t dictybase/dicty-stock-center:ericdev-develop-$(git rev-parse --short HEAD) -f docker/eric-dev/Dockerfile .
  #     - name: build devsidd docker image
  #       run: docker build -t dictybase/dicty-stock-center:devsidd-develop-$(git rev-parse --short HEAD) -f docker/sidd-dev/Dockerfile .
  #     - name: login to docker hub
  #       run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
  #     - name: push ericdev to docker hub
  #       run: docker push dictybase/dicty-stock-center:ericdev-develop-$(git rev-parse --short HEAD)
  #     - name: push devsidd to docker hub
  #       run: docker push dictybase/dicty-stock-center:devsidd-develop-$(git rev-parse --short HEAD)
  # sleep:
  #   needs: build
  #   runs-on: ubuntu-18.04
  #   steps:
  #     # sleep to ensure that this image has been pushed to the cluster
  #     - name: sleep for three minutes
  #       run: sleep 180
  cypress:
    # needs: sleep
    runs-on: ubuntu-18.04
    steps:
      - name: set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: check out code
        uses: actions/checkout@v1
      - name: cache cypress binary
        uses: actions/cache@v1
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-
      - name: cache local node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: install dependencies
        run: npm ci
      - name: run cypress and percy tests
        run: npm run cypress:run
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CI: true
  # audit:
  #   needs: sleep
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: audit live URL
  #       uses: docker://dictybase/lighthouse-audit:latest
  #       with:
  #         url: "https://eric.dictybase.dev/stockcenter"
  #       env:
  #         GH_TOKEN: ${{ secrets.GH_TOKEN}}
  #         BUCKET_PATH: https://ericstorage.dictybase.dev/lighthouse
  #     - name: upload results as an artifact
  #       uses: actions/upload-artifact@master
  #       with:
  #         name: report
  #         path: "./report"
  #     - name: upload results to minio
  #       uses: docker://dictybase/file-uploader:latest
  #       with:
  #         args: "minio --folder report --minio-bucket lighthouse"
  #       env:
  #         MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
  #         MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
  # snapshots:
  #   needs: sleep
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: set up node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 10.x
  #     - name: check out code
  #       uses: actions/checkout@v1
  #     - name: generate snapshots
  #       run: |
  #         npm i nightwatch chromedriver
  #         npm run nightwatch
  #     - name: upload snapshots as artifact
  #       uses: actions/upload-artifact@master
  #       with:
  #         name: snapshots
  #         path: "./nightwatch/reports"
  #     - name: upload snapshots to minio
  #       uses: docker://dictybase/file-uploader:latest
  #       with:
  #         args: "minio --folder ./nightwatch/reports --minio-bucket snapshots"
  #       env:
  #         MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
  #         MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
  #     - name: add snapshots to github issue
  #       uses: docker://dictybase/snapshot-issue-creator:latest
  #       env:
  #         GH_TOKEN: ${{ secrets.GH_TOKEN}}
  #         BUCKET_PATH: https://ericstorage.dictybase.dev/snapshots
  #         FILE_PATH: "./nightwatch/reports"
