name: Package size report
on:
  pull_request:
    types: [edited, labeled, opened, synchronize, reopened]
jobs:
  size:
    runs-on: ubuntu-20.04
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: rename config file
        run: mv src/common/utils/clientConfig.sample.ts src/common/utils/clientConfig.ts
      - name: calculate app size
        uses: andresz1/size-limit-action@v1.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
