name: TSC
on: pull_request
jobs:
  eslint:
    runs-on: ubuntu-18.04
    steps:
      - name: set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: check out code
        uses: actions/checkout@v1
      - name: npm install
        run: npm install
      - name: tsc
        run: |
          mv src/common/utils/clientConfig.sample.ts src/common/utils/clientConfig.ts
          npm run tsc
